repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-fmt
      - id: clippy
        args: ["--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0
    hooks:
      - id: prettier
        files: \.(md|json|yml|yaml)$

  - repo: local
    hooks:
      - id: cargo-deny
        name: cargo deny
        entry: cargo deny check
        language: system
        files: Cargo.toml
        pass_filenames: false

      - id: cargo-audit
        name: cargo audit
        entry: cargo audit
        language: system
        files: Cargo.lock
        pass_filenames: false
