global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: sonar-coordinator
    static_configs:
      - targets:
          - coordinator:9090

  - job_name: sonar-prover
    static_configs:
      - targets:
          - prover:9091
